### PR TITLE
Ported mod to Forge

### PR DESCRIPTION
**Pull request by 22ms**
Ported the mod to forge 1.20.1 for personal use, if you want to merge, go ahead
(Alternate recipes don't work yet)

### CODE REVIEW

**Comment by l00nz** [comment]
Hey, thanks for porting!

I'll change the repo structure to allow Fabric and Forge to be in the same repo without any conflicts
After that I'll merge your changes

**Comment by l00nz** [comment]
Just a quick update.

Since the repo has been restructured, I need to move a lot of files.
I'm almost done and will finish + merge changes tomorrow

**Comment by 22ms** [comment]
Nice, if you need help with anything let me know

**Comment by l00nz** [comment]
Finnaly Merged!! 
Should all be configuted correctly.
If you find anything weird, just submit an Issues or do another pull request

**Comment by l00nz** [comment]
Btw, would it be okay for you, If I publish a the forge build on modrinth and Curseforge?
I'll give you credit ofc

**Comment by 22ms** [comment]
Sure, I'd like that. Btw, did you implement the shapeless recipes for forge? If not, I can try when I'm free

**Comment by 22ms** [comment]
Oh, du bist ja Deutscher

**Comment by l00nz** [comment]
> Sure, I'd like that. Btw, did you implement the shapeless recipes for forge? If not, I can try when I'm free

If I have time today, I'll try to implement it.

> Oh, du bist ja Deutscher

Ja. Gesehen durch die "de_de.json"?

Würde aber gerne die Konversationen auf Englisch halten, fals jemand anderes zufälligerweise am Projekt mitarbeiten will

**Pull request merged**
